#include <stdio.h>
#include <stdint.h>
#include "kernel.h"

// Lookup table indexed by import number. NULL = not stubbed.
void* kernel_table[512] = {
	// Av
	[1]   = stub_AvGetSavedDataAddress,
	[2]   = stub_AvSendTVEncoderOption,
	[3]   = stub_AvSetDisplayMode,
	[4]   = stub_AvSetSavedDataAddress,
	// Dbg
	[8]   = stub_DbgPrint,
	// Ex
	[24]  = stub_ExQueryNonVolatileSetting,
	// Hal
	[44]  = stub_HalGetInterruptVector,
	[46]  = stub_HalReadWritePCISpace,
	[49]  = stub_HalReturnToFirmware,
	// Interlocked
	[54]  = stub_InterlockedExchange,
	// Io
	[67]  = stub_IoCreateSymbolicLink,
	[69]  = stub_IoDeleteSymbolicLink,
	// Ke
	[98]  = stub_KeConnectInterrupt,
	[99]  = stub_KeDelayExecutionThread,
	[103] = stub_KeGetCurrentIrql,
	[104] = stub_KeGetCurrentThread,
	[107] = stub_KeInitializeDpc,
	[109] = stub_KeInitializeInterrupt,
	[119] = stub_KeInsertQueueDpc,
	[128] = stub_KeQuerySystemTime,
	[143] = stub_KeSetBasePriorityThread,
	// Mm
	[164] = stub_LaunchDataPage,
	[165] = stub_MmAllocateContiguousMemory,
	[166] = stub_MmAllocateContiguousMemoryEx,
	[171] = stub_MmFreeContiguousMemory,
	[178] = stub_MmPersistContiguousMemory,
	[180] = stub_MmQueryAllocationSize,
	// Nt
	[184] = stub_NtAllocateVirtualMemory,
	[186] = stub_NtClearEvent,
	[187] = stub_NtClose,
	[189] = stub_NtCreateEvent,
	[190] = stub_NtCreateFile,
	[192] = stub_NtCreateMutant,
	[193] = stub_NtCreateSemaphore,
	[199] = stub_NtFreeVirtualMemory,
	[201] = stub_NtOpenDirectoryObject,
	[202] = stub_NtOpenFile,
	[203] = stub_NtOpenSymbolicLinkObject,
	[205] = stub_NtPulseEvent,
	[208] = stub_NtQueryDirectoryObject,
	[210] = stub_NtQueryFullAttributesFile,
	[211] = stub_NtQueryInformationFile,
	[217] = stub_NtQueryVirtualMemory,
	[218] = stub_NtQueryVolumeInformationFile,
	[219] = stub_NtReadFile,
	[221] = stub_NtReleaseMutant,
	[222] = stub_NtReleaseSemaphore,
	[224] = stub_NtResumeThread,
	[225] = stub_NtSetEvent,
	[226] = stub_NtSetInformationFile,
	[231] = stub_NtSuspendThread,
	[233] = stub_NtWaitForSingleObject,
	[234] = stub_NtWaitForSingleObjectEx,
	[235] = stub_NtWaitForMultipleObjectsEx,
	[236] = stub_NtWriteFile,
	[238] = stub_NtYieldExecution,
	// Ob
	[246] = stub_ObReferenceObjectByHandle,
	[250] = stub_ObfDereferenceObject,
	// Ps
	[255] = stub_PsCreateSystemThreadEx,
	[258] = stub_PsTerminateSystemThread,
	[259] = stub_PsThreadObjectType,
	// Rtl
	[277] = stub_RtlEnterCriticalSection,
	[289] = stub_RtlInitAnsiString,
	[291] = stub_RtlInitializeCriticalSection,
	[294] = stub_RtlLeaveCriticalSection,
	[301] = stub_RtlNtStatusToDosError,
	[302] = stub_RtlRaiseException,
	[306] = stub_RtlTryEnterCriticalSection,
	// Xc
	[335] = stub_XcSHAInit,
	[336] = stub_XcSHAUpdate,
	[337] = stub_XcSHAFinal,
	// Xe
	[326] = stub_XeImageFileName,
	// Additional stubs
	[15]  = stub_ExAllocatePool,
	[17]  = stub_ExFreePool,
	[66]  = stub_IoCreateFile,
	[70]  = stub_IoDeviceObjectType,
	[79]  = stub_IoSetIoCompletion,
	[80]  = stub_IoSetShareAccess,
	[95]  = stub_KeBugCheck,
	[117] = stub_KeInsertQueue,
	[126] = stub_KeQueryPerformanceCounter,
	[131] = stub_KeReleaseMutant,
	[137] = stub_KeRemoveQueueDpc,
	[139] = stub_KeRestoreFloatingPointState,
	[156] = &stub_KeTickCount,
	[198] = stub_NtFlushBuffersFile,
	[256] = stub_PsQueryStatistics,
	[260] = stub_RtlAnsiStringToUnicodeString,
	[272] = stub_RtlCopyString,
	[292] = stub_RtlIntegerToChar,
	[358] = stub_HalIsResetOrShutdownPending,
	// Ex
	[12]  = stub_ExAcquireReadWriteLockExclusive,
	[13]  = stub_ExAcquireReadWriteLockShared,
	[16]  = stub_ExEventObjectType,
	[19]  = stub_ExInterlockedAddLargeInteger,
	[20]  = stub_ExInterlockedAddLargeStatistic,
	[21]  = stub_ExInterlockedCompareExchange64,
	[22]  = stub_ExMutantObjectType,
	[28]  = stub_ExReleaseReadWriteLock,
	[30]  = stub_ExSemaphoreObjectType,
	[31]  = stub_ExTimerObjectType,
	[32]  = stub_ExfInterlockedInsertHeadList,
	[33]  = stub_ExfInterlockedInsertTailList,
	[34]  = stub_ExfInterlockedRemoveHeadList,
	// Interlocked
	[51]  = stub_InterlockedCompareExchange,
	[52]  = stub_InterlockedDecrement,
	[53]  = stub_InterlockedIncrement,
	[57]  = stub_InterlockedPopEntrySList,
	[58]  = stub_InterlockedPushEntrySList,
	// Io
	[59]  = stub_IoAllocateIrp,
	[64]  = stub_IoCompletionObjectType,
	[65]  = stub_IoCreateDevice,
	[68]  = stub_IoDeleteDevice,
	[71]  = stub_IoFileObjectType,
	[72]  = stub_IoFreeIrp,
	[77]  = stub_IoQueueThreadIrp,
	[85]  = stub_IoSynchronousFsdRequest,
	[86]  = stub_IofCallDriver,
	[87]  = stub_IofCompleteRequest,
	// Kd
	[88]  = &stub_KdDebuggerEnabled,
	[89]  = &stub_KdDebuggerNotPresent,
	// Ke
	[94]  = stub_KeBoostPriorityThread,
	[101] = stub_KeEnterCriticalRegion,
	[102] = stub_MmGlobalData,
	[110] = stub_KeInitializeMutant,
	[111] = stub_KeInitializeQueue,
	[113] = stub_KeInitializeTimerEx,
	[114] = stub_KeInsertByKeyDeviceQueue,
	[115] = stub_KeInsertDeviceQueue,
	[116] = stub_KeInsertHeadQueue,
	[120] = &stub_KeInterruptTime,
	[122] = stub_KeLeaveCriticalRegion,
	[123] = stub_KePulseEvent,
	[125] = stub_KeQueryInterruptTime,
	[129] = stub_KeRaiseIrqlToDpcLevel,
	[132] = stub_KeReleaseSemaphore,
	[133] = stub_KeRemoveByKeyDeviceQueue,
	[134] = stub_KeRemoveDeviceQueue,
	[135] = stub_KeRemoveEntryDeviceQueue,
	[138] = stub_KeResetEvent,
	[141] = stub_KeRundownQueue,
	[149] = stub_KeSetTimer,
	[150] = stub_KeSetTimerEx,
	[155] = stub_KeTestAlertThread,
	[158] = stub_KeWaitForMultipleObjects,
	[159] = stub_KeWaitForSingleObject,
	[160] = stub_KfRaiseIrql,
	[161] = stub_KfLowerIrql,
	[162] = stub_KiBugCheckData,
	// Mm
	[183] = stub_MmUnmapIoSpace,
	// Nt
	[194] = stub_NtCreateTimer,
	[196] = stub_NtDeviceIoControlFile,
	[200] = stub_NtFsControlFile,
	[204] = stub_NtProtectVirtualMemory,
	[206] = stub_NtQueueApcThread,
	[216] = stub_NtQueryTimer,
	[232] = stub_NtUserIoApcDispatcher,
	// Ob
	[240] = stub_ObDirectoryObjectType,
	[248] = stub_ObReferenceObjectByPointer,
	[249] = stub_ObSymbolicLinkObjectType,
	[251] = stub_ObfReferenceObject,
	// Phy
	[252] = stub_PhyGetLinkState,
	// Ps
	[254] = stub_PsCreateSystemThread,
	// Rtl
	[262] = stub_RtlAppendUnicodeStringToString,
	[263] = stub_RtlAppendUnicodeToString,
	[267] = stub_RtlCharToInteger,
	[268] = stub_RtlCompareMemory,
	[270] = stub_RtlCompareString,
	[271] = stub_RtlCompareUnicodeString,
	[273] = stub_RtlCopyUnicodeString,
	[274] = stub_RtlCreateUnicodeString,
	[279] = stub_RtlEqualString,
	[280] = stub_RtlEqualUnicodeString,
	[286] = stub_RtlFreeAnsiString,
	[287] = stub_RtlFreeUnicodeString,
	[288] = stub_RtlGetCallersAddress,
	[293] = stub_RtlIntegerToUnicodeString,
	[299] = stub_RtlMultiByteToUnicodeN,
	[300] = stub_RtlMultiByteToUnicodeSize,
	[307] = stub_RtlUlongByteSwap,
	[308] = stub_RtlUnicodeStringToAnsiString,
	[313] = stub_RtlUpcaseUnicodeChar,
	[314] = stub_RtlUpcaseUnicodeString,
	[315] = stub_RtlUpcaseUnicodeToMultiByteN,
	// Xbox data
	[321] = stub_XboxEEPROMKey,
	[323] = stub_XboxHDKey,
	[325] = stub_XboxSignatureKey,
};
