#include <stdio.h>
#include <stdint.h>

extern void* kernel_table[512];

// === Nt functions (kernel_nt.c) ===
uint32_t __stdcall stub_NtAllocateVirtualMemory(void** BaseAddress, uint32_t ZeroBits, uint32_t* AllocationSize, uint32_t AllocationType, uint32_t Protect);
uint32_t __stdcall stub_NtClearEvent(uint32_t EventHandle);
uint32_t __stdcall stub_NtClose(uint32_t Handle);
uint32_t __stdcall stub_NtCreateEvent(void* EventHandle, void* ObjectAttributes, uint32_t EventType, uint32_t InitialState);
uint32_t __stdcall stub_NtCreateFile(void* FileHandle, uint32_t DesiredAccess, void* ObjectAttributes, void* IoStatusBlock, void* AllocationSize, uint32_t FileAttributes, uint32_t ShareAccess, uint32_t CreateDisposition, uint32_t CreateOptions);
uint32_t __stdcall stub_NtCreateMutant(void* MutantHandle, void* ObjectAttributes, uint32_t InitialOwner);
uint32_t __stdcall stub_NtCreateSemaphore(void* SemaphoreHandle, void* ObjectAttributes, uint32_t InitialCount, uint32_t MaximumCount);
uint32_t __stdcall stub_NtFreeVirtualMemory(void** BaseAddress, uint32_t* FreeSize, uint32_t FreeType);
uint32_t __stdcall stub_NtOpenDirectoryObject(void* DirectoryHandle, void* ObjectAttributes);
uint32_t __stdcall stub_NtOpenFile(void* FileHandle, uint32_t DesiredAccess, void* ObjectAttributes, void* IoStatusBlock, uint32_t ShareAccess, uint32_t OpenOptions);
uint32_t __stdcall stub_NtOpenSymbolicLinkObject(void* LinkHandle, void* ObjectAttributes);
uint32_t __stdcall stub_NtPulseEvent(uint32_t EventHandle, void* PreviousState);
uint32_t __stdcall stub_NtQueryDirectoryObject(uint32_t DirectoryHandle, void* Buffer, uint32_t Length, uint32_t RestartScan, uint32_t* Context, uint32_t* ReturnLength);
uint32_t __stdcall stub_NtQueryFullAttributesFile(void* ObjectAttributes, void* FileInformation);
uint32_t __stdcall stub_NtQueryInformationFile(uint32_t FileHandle, void* IoStatusBlock, void* FileInformation, uint32_t Length, uint32_t FileInformationClass);
uint32_t __stdcall stub_NtQueryVirtualMemory(void* BaseAddress, void* Buffer);
uint32_t __stdcall stub_NtQueryVolumeInformationFile(uint32_t FileHandle, void* IoStatusBlock, void* FileInformation, uint32_t Length, uint32_t FileInformationClass);
uint32_t __stdcall stub_NtReadFile(uint32_t FileHandle, uint32_t Event, void* ApcRoutine, void* ApcContext, void* IoStatusBlock, void* Buffer, uint32_t Length, void* ByteOffset);
uint32_t __stdcall stub_NtReleaseMutant(uint32_t MutantHandle, void* PreviousCount);
uint32_t __stdcall stub_NtReleaseSemaphore(uint32_t SemaphoreHandle, uint32_t ReleaseCount, uint32_t* PreviousCount);
uint32_t __stdcall stub_NtResumeThread(uint32_t ThreadHandle, uint32_t* PreviousSuspendCount);
uint32_t __stdcall stub_NtSetEvent(uint32_t EventHandle, void* PreviousState);
uint32_t __stdcall stub_NtSetInformationFile(uint32_t FileHandle, void* IoStatusBlock, void* FileInformation, uint32_t Length, uint32_t FileInformationClass);
uint32_t __stdcall stub_NtSuspendThread(uint32_t ThreadHandle, uint32_t* PreviousSuspendCount);
uint32_t __stdcall stub_NtWaitForSingleObject(uint32_t Handle, uint32_t Alertable, void* Timeout);
uint32_t __stdcall stub_NtWaitForSingleObjectEx(uint32_t Handle, uint32_t WaitMode, uint32_t Alertable, void* Timeout);
uint32_t __stdcall stub_NtWaitForMultipleObjectsEx(uint32_t Count, void* Handles, uint32_t WaitType, uint32_t WaitMode, uint32_t Alertable, void* Timeout);
uint32_t __stdcall stub_NtWriteFile(uint32_t FileHandle, uint32_t Event, void* ApcRoutine, void* ApcContext, void* IoStatusBlock, void* Buffer, uint32_t Length, void* ByteOffset);
void __stdcall stub_NtYieldExecution(void);

// === Xc functions (kernel_Xc.c) ===
uint32_t __stdcall stub_XcSHAInit(void* pbSHAContext);
void __stdcall stub_XcSHAUpdate(void* pbSHAContext, void* pbInput, uint32_t dwInputLength);
void __stdcall stub_XcSHAFinal(void* pbSHAContext, void* pbDigest);

// === Misc functions (kernel_misc.c) ===
void* __stdcall stub_AvGetSavedDataAddress(void);
void __stdcall stub_AvSendTVEncoderOption(void* RegisterBase, uint32_t Option, uint32_t Param, uint32_t* Result);
uint32_t __stdcall stub_AvSetDisplayMode(void* RegisterBase, uint32_t Step, uint32_t Mode, uint32_t Format, uint32_t Pitch, void* FrameBuffer);
void __stdcall stub_AvSetSavedDataAddress(void* Address);
uint32_t __cdecl stub_DbgPrint(char* Format, ...);
uint32_t __stdcall stub_ExQueryNonVolatileSetting(uint32_t ValueIndex, uint32_t* Type, void* Value, uint32_t ValueLength, void* ResultLength);
uint32_t __stdcall stub_HalGetInterruptVector(uint32_t BusInterruptLevel, void* Irql);
void __stdcall stub_HalReadWritePCISpace(uint32_t BusNumber, uint32_t SlotNumber, uint32_t RegisterNumber, void* Buffer, uint32_t Length, uint32_t WritePCISpace);
void __stdcall stub_HalReturnToFirmware(uint32_t Routine);
uint32_t __fastcall stub_InterlockedExchange(void* Destination, uint32_t Value);
uint32_t __stdcall stub_IoCreateSymbolicLink(void* SymbolicLinkName, void* DeviceName);
uint32_t __stdcall stub_IoDeleteSymbolicLink(void* SymbolicLinkName);
uint32_t __stdcall stub_KeConnectInterrupt(void* InterruptObject);
uint32_t __stdcall stub_KeDelayExecutionThread(uint32_t WaitMode, uint32_t Alertable, void* Interval);
uint32_t __stdcall stub_KeGetCurrentIrql(void);
void* __stdcall stub_KeGetCurrentThread(void);
void __stdcall stub_KeInitializeDpc(void* Dpc, void* DeferredRoutine, void* DeferredContext);
void __stdcall stub_KeInitializeInterrupt(void* Interrupt, void* ServiceRoutine, void* ServiceContext, uint32_t Vector, uint32_t Irql, uint32_t InterruptMode, uint32_t ShareVector);
uint32_t __stdcall stub_KeInsertQueueDpc(void* Dpc, void* SystemArgument1, void* SystemArgument2);
void __stdcall stub_KeQuerySystemTime(void* CurrentTime);
uint32_t __stdcall stub_KeSetBasePriorityThread(void* Thread, uint32_t Priority);
void* __stdcall stub_MmAllocateContiguousMemory(uint32_t NumberOfBytes);
void* __stdcall stub_MmAllocateContiguousMemoryEx(uint32_t NumberOfBytes, uint32_t LowestAddr, uint32_t HighestAddr, uint32_t Alignment, uint32_t ProtectionType);
void __stdcall stub_MmFreeContiguousMemory(void* BaseAddress);
void __stdcall stub_MmPersistContiguousMemory(void* BaseAddress, uint32_t NumberOfBytes, uint32_t Persist);
uint32_t __stdcall stub_MmQueryAllocationSize(void* BaseAddress);
uint32_t __stdcall stub_ObReferenceObjectByHandle(uint32_t Handle, void* ObjectType, void** ReturnedObject);
void __fastcall stub_ObfDereferenceObject(void* Object);
uint32_t __stdcall stub_PsCreateSystemThreadEx(void* ThreadHandle, uint32_t ThreadExtensionSize, uint32_t KernelStackSize, uint32_t TlsDataSize, void* ThreadId, void* StartRoutine, void* StartContext, uint32_t CreateSuspended, uint32_t DebugStack, void* SystemRoutine);
void __stdcall stub_PsTerminateSystemThread(uint32_t ExitStatus);
void __stdcall stub_RtlEnterCriticalSection(void* CriticalSection);
void __stdcall stub_RtlInitAnsiString(void* DestinationString, void* SourceString);
void __stdcall stub_RtlInitializeCriticalSection(void* CriticalSection);
void __stdcall stub_RtlLeaveCriticalSection(void* CriticalSection);
uint32_t __stdcall stub_RtlNtStatusToDosError(uint32_t Status);
void __stdcall stub_RtlRaiseException(void* ExceptionRecord);
uint32_t __stdcall stub_RtlTryEnterCriticalSection(void* CriticalSection);

// Data exports (addresses of static buffers)
extern uint8_t stub_LaunchDataPage[];
extern uint8_t stub_PsThreadObjectType[];
extern uint8_t stub_XeImageFileName[];
extern uint8_t stub_IoDeviceObjectType[];
extern uint32_t stub_KeTickCount;

// Added stubs
void* __stdcall stub_ExAllocatePool(uint32_t NumberOfBytes);
void __stdcall stub_ExFreePool(void* P);
uint32_t __stdcall stub_IoCreateFile(void* FileHandle, uint32_t a, void* b, void* c, void* d, uint32_t e, uint32_t f, uint32_t g, uint32_t h, uint32_t i);
uint32_t __stdcall stub_IoSetIoCompletion(void* a, void* b, void* c, uint32_t d, uint32_t e);
uint32_t __stdcall stub_IoSetShareAccess(uint32_t a, uint32_t b, void* c, void* d);
void __stdcall stub_KeBugCheck(uint32_t Code);
uint32_t __stdcall stub_KeInsertQueue(void* Queue, void* Entry);
void __stdcall stub_KeQueryPerformanceCounter(void* out);
uint32_t __stdcall stub_KeReleaseMutant(void* m, uint32_t a, uint32_t b, uint32_t c);
uint32_t __stdcall stub_KeRemoveQueueDpc(void* Dpc);
uint32_t __stdcall stub_KeRestoreFloatingPointState(void* Save);
uint32_t __stdcall stub_NtFlushBuffersFile(void* a, void* b);
uint32_t __stdcall stub_PsQueryStatistics(void* Stats);
uint32_t __stdcall stub_RtlAnsiStringToUnicodeString(void* a, void* b, uint32_t c);
void __stdcall stub_RtlCopyString(void* a, void* b);
uint32_t __stdcall stub_RtlIntegerToChar(uint32_t a, uint32_t b, uint32_t c, void* d);
uint32_t __stdcall stub_HalIsResetOrShutdownPending(void);

// Big batch
extern uint8_t stub_ExEventObjectType[];
extern uint8_t stub_ExMutantObjectType[];
extern uint8_t stub_ExSemaphoreObjectType[];
extern uint8_t stub_ExTimerObjectType[];
extern uint8_t stub_IoFileObjectType[];
extern uint8_t stub_IoCompletionObjectType[];
extern uint8_t stub_ObDirectoryObjectType[];
extern uint8_t stub_ObSymbolicLinkObjectType[];
extern uint8_t stub_MmGlobalData[];
extern uint8_t stub_XboxEEPROMKey[];
extern uint8_t stub_XboxHDKey[];
extern uint8_t stub_XboxSignatureKey[];
extern uint8_t stub_KiBugCheckData[];
extern uint32_t stub_KdDebuggerEnabled;
extern uint32_t stub_KdDebuggerNotPresent;
extern uint64_t stub_KeInterruptTime;

void __stdcall stub_ExAcquireReadWriteLockExclusive(void* Lock);
void __stdcall stub_ExAcquireReadWriteLockShared(void* Lock);
void __stdcall stub_ExInterlockedAddLargeInteger(void* a, uint32_t b, uint32_t c);
void __stdcall stub_ExInterlockedAddLargeStatistic(void* a, uint32_t b);
uint64_t __stdcall stub_ExInterlockedCompareExchange64(void* a, void* b, void* c);
void __stdcall stub_ExReleaseReadWriteLock(void* Lock);
void __stdcall stub_ExfInterlockedInsertHeadList(void* a, void* b);
void __stdcall stub_ExfInterlockedInsertTailList(void* a, void* b);
void* __stdcall stub_ExfInterlockedRemoveHeadList(void* a);
uint32_t __fastcall stub_InterlockedCompareExchange(void* Dest, uint32_t Exch, uint32_t Comp);
uint32_t __fastcall stub_InterlockedIncrement(uint32_t* v);
uint32_t __fastcall stub_InterlockedDecrement(uint32_t* v);
void* __fastcall stub_InterlockedPopEntrySList(void* Head);
void* __fastcall stub_InterlockedPushEntrySList(void* Head, void* Entry);
void* __stdcall stub_IoAllocateIrp(uint32_t Size, uint32_t ChargeQuota);
uint32_t __stdcall stub_IoCreateDevice(void* a, uint32_t b, void* c, uint32_t d, uint32_t e, uint32_t f, void** g);
uint32_t __stdcall stub_IoDeleteDevice(void* a);
void __stdcall stub_IoFreeIrp(void* Irp);
uint32_t __stdcall stub_IoQueueThreadIrp(void* Irp);
uint32_t __stdcall stub_IoSynchronousFsdRequest(uint32_t a, void* b, void* c, uint32_t d, void* e, void* f, uint32_t g);
uint32_t __fastcall stub_IofCallDriver(void* Dev, void* Irp);
void __fastcall stub_IofCompleteRequest(void* Irp, uint32_t Boost);
void __stdcall stub_KeBoostPriorityThread(void* Thread, uint32_t Inc);
void __stdcall stub_KeEnterCriticalRegion(void);
void __stdcall stub_KeLeaveCriticalRegion(void);
void __stdcall stub_KeInitializeMutant(void* M, uint32_t Owner);
void __stdcall stub_KeInitializeQueue(void* Q, uint32_t Count);
void __stdcall stub_KeInitializeTimerEx(void* T, uint32_t Type);
uint32_t __stdcall stub_KeInsertDeviceQueue(void* Q, void* E);
uint32_t __stdcall stub_KeInsertByKeyDeviceQueue(void* Q, void* E, uint32_t K);
uint32_t __stdcall stub_KeInsertHeadQueue(void* Q, void* E);
void __stdcall stub_KePulseEvent(void* E, uint32_t Inc, uint32_t Wait);
uint64_t __stdcall stub_KeQueryInterruptTime(void);
uint32_t __stdcall stub_KeRaiseIrqlToDpcLevel(void);
uint32_t __stdcall stub_KeReleaseSemaphore(void* S, uint32_t Inc, uint32_t Adj, uint32_t Wait);
void* __stdcall stub_KeRemoveDeviceQueue(void* Q);
void* __stdcall stub_KeRemoveByKeyDeviceQueue(void* Q, uint32_t K);
uint32_t __stdcall stub_KeRemoveEntryDeviceQueue(void* Q, void* E);
uint32_t __stdcall stub_KeResetEvent(void* E);
void __stdcall stub_KeRundownQueue(void* Q);
uint32_t __stdcall stub_KeSetTimer(void* T, uint64_t DueTime, void* Dpc);
uint32_t __stdcall stub_KeSetTimerEx(void* T, uint64_t DueTime, uint32_t Period, void* Dpc);
uint32_t __stdcall stub_KeTestAlertThread(uint32_t Mode);
uint32_t __stdcall stub_KeWaitForSingleObject(void* O, uint32_t Reason, uint32_t Mode, uint32_t Alert, void* Timeout);
uint32_t __stdcall stub_KeWaitForMultipleObjects(uint32_t Count, void* Objs, uint32_t Type, uint32_t Reason, uint32_t Mode, uint32_t Alert, void* Timeout, void* Wait);
uint32_t __fastcall stub_KfLowerIrql(uint32_t Irql);
uint32_t __fastcall stub_KfRaiseIrql(uint32_t Irql);
void __stdcall stub_MmUnmapIoSpace(void* a, uint32_t b);
uint32_t __stdcall stub_NtCreateTimer(void* H, void* OA, uint32_t Type);
uint32_t __stdcall stub_NtDeviceIoControlFile(uint32_t H, uint32_t E, void* A, void* AC, void* IOSB, uint32_t Code, void* In, uint32_t InLen, void* Out, uint32_t OutLen);
uint32_t __stdcall stub_NtFsControlFile(uint32_t H, uint32_t E, void* A, void* AC, void* IOSB, uint32_t Code, void* In, uint32_t InLen, void* Out, uint32_t OutLen);
uint32_t __stdcall stub_NtProtectVirtualMemory(void** BA, uint32_t* Size, uint32_t Prot, uint32_t* Old);
uint32_t __stdcall stub_NtQueueApcThread(uint32_t Th, void* R, void* Ctx, void* A1, void* A2);
uint32_t __stdcall stub_NtQueryTimer(uint32_t H, uint32_t Cls, void* Info);
uint32_t __stdcall stub_NtUserIoApcDispatcher(void* Ctx, void* IOSB, uint32_t Rsv);
uint32_t __stdcall stub_ObReferenceObjectByPointer(void* O, void* T);
void __fastcall stub_ObfReferenceObject(void* O);
uint32_t __stdcall stub_PhyGetLinkState(uint32_t Flags);
uint32_t __stdcall stub_PsCreateSystemThread(void* H, void* OA, void* SR, void* SC, uint32_t Dbg);
uint32_t __stdcall stub_RtlAppendUnicodeStringToString(void* D, void* S);
uint32_t __stdcall stub_RtlAppendUnicodeToString(void* D, void* S);
uint32_t __stdcall stub_RtlCharToInteger(char* S, uint32_t Base, uint32_t* V);
uint32_t __stdcall stub_RtlCompareMemory(void* a, void* b, uint32_t Len);
uint32_t __stdcall stub_RtlCompareString(void* a, void* b, uint32_t Case);
uint32_t __stdcall stub_RtlCompareUnicodeString(void* a, void* b, uint32_t Case);
void __stdcall stub_RtlCopyUnicodeString(void* D, void* S);
void __stdcall stub_RtlCreateUnicodeString(void* D, void* S);
uint32_t __stdcall stub_RtlEqualString(void* a, void* b, uint32_t Case);
uint32_t __stdcall stub_RtlEqualUnicodeString(void* a, void* b, uint32_t Case);
void __stdcall stub_RtlFreeAnsiString(void* S);
void __stdcall stub_RtlFreeUnicodeString(void* S);
void __stdcall stub_RtlGetCallersAddress(void** Caller, void** Parent);
uint32_t __stdcall stub_RtlIntegerToUnicodeString(uint32_t V, uint32_t Base, void* S);
uint32_t __stdcall stub_RtlMultiByteToUnicodeN(void* U, uint32_t UMax, uint32_t* URet, void* M, uint32_t MLen);
uint32_t __stdcall stub_RtlMultiByteToUnicodeSize(uint32_t* Sz, void* M, uint32_t MLen);
uint32_t __stdcall stub_RtlUlongByteSwap(uint32_t V);
uint32_t __stdcall stub_RtlUnicodeStringToAnsiString(void* D, void* S, uint32_t Alloc);
uint16_t __stdcall stub_RtlUpcaseUnicodeChar(uint16_t C);
uint32_t __stdcall stub_RtlUpcaseUnicodeString(void* D, void* S, uint32_t Alloc);
uint32_t __stdcall stub_RtlUpcaseUnicodeToMultiByteN(void* M, uint32_t MMax, uint32_t* MRet, void* U, uint32_t ULen);
